### ISSUE TITLE
Please republish a new version

### ISSUE THREAD

**Issue by Genide** [electron-react-boilerplate/eslint-config-erb#138]
### Steps to reproduce:

1. Clone ERB electron-react-boilerplate repo. https://github.com/electron-react-boilerplate/electron-react-boilerplate
2. npm install
2. Upgrade typescript version to latest (4.5.0 or higher)
3. npm run lint

### Error Information

> PS C:\Projects\electron-builder-test> npm run lint
> 
> > lint
> > cross-env NODE_ENV=development eslint . --ext .js,.jsx,.ts,.tsx
> 
> =============
> 
> WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
> 
> You may find that it works just fine, or you may not.
> 
> SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0
> 
> YOUR TYPESCRIPT VERSION: 4.5.5
> 
> Please only submit bug reports when using the officially supported version.
> 
> =============

### Problematic Package Location
Looking for the outdated @typescript-eslint/typescript-estree shows that it is within the eslint-config-erb package.
![image](https://user-images.githubusercontent.com/10857365/152630110-be478459-389e-4674-ba54-49bb6112ade6.png)

### Suggested Solution
Please release a new version of eslint-config-erb with the updated dependencies. Looking at the master branch, it looks like the dependency upgrade work was already done in d1434db3b7423460ce02e1673b2408dac3a53214.

**Comment by amilajack** [comment]
I'll get to this soon, thanks for filing this

**Comment by amilajack** [comment]
just cut eslint-config-erb@4.0.5
